"""Real pinned precision fixtures for Phase 2I owner semantics."""

from collections import Counter

from knowledge.champion_spell_stat_owner_semantics import (
    OWNER_CONTEXT_DEPENDENT,
    OWNER_UNRESOLVED,
    build_owner_contracts,
    build_owner_records,
    inventory_owner_occurrences,
)
from knowledge.champion_spell_stat_owner_sources import PINNED_DATAMINE_COMMIT
from knowledge.pinned_spell_catalog_cache import get_pinned_spell_catalog


# Expected identities are fixed from the pinned graph, not generated by the
# owner resolver.  They intentionally span unrelated champions and mechanics.
REAL_CONTEXT_FIXTURES = [
    ("Aatrox", "Q", "QDamage", "mSpellCalculations/QDamage/mFormulaParts/1"),
    ("Akshan", "Q", "FinalDamage", "mSpellCalculations/FinalDamage/mFormulaParts/1"),
    ("Diana", "W", "ShieldValue", "mSpellCalculations/ShieldValue/mFormulaParts/2"),
    ("Malphite", "E", "EDamageCalc", "mSpellCalculations/EDamageCalc/mFormulaParts/1"),
    ("Shyvana", "Q", "Calc_Damage", "mSpellCalculations/Calc_Damage/mFormulaParts/1"),
    ("Belveth", "Q", "baseDamage", "mSpellCalculations/baseDamage/mFormulaParts/1"),
    ("DrMundo", "W", "TotalDamage", "mSpellCalculations/TotalDamage/mFormulaParts/1"),
    ("Viego", "Q", "SecondAttackDamage", "mSpellCalculations/SecondAttackDamage/mFormulaParts/0"),
    ("Rammus", "W", "BonusArmorTooltip", "mSpellCalculations/BonusArmorTooltip/mFormulaParts/1"),
]

UNKNOWN_HASH_FIXTURES = [
    ("Ekko", "W", "mSpellCalculations/0x79b6144b/mMultiplier"),
    ("Kindred", "W", "mSpellCalculations/0xfe248f68/mMultiplier"),
]


def main():
    catalog = get_pinned_spell_catalog()
    rows = inventory_owner_occurrences(catalog)
    contracts = build_owner_contracts(rows)
    records = build_owner_records(rows, contracts)
    by_identity = {
        (record["champion"], record["slot"], record["calculation_key"], record["graph_path"]): record
        for record in records
    }
    checks = 0

    assert len(rows) == 569
    assert len(contracts) == 88
    assert catalog["source_commit"] == PINNED_DATAMINE_COMMIT
    checks += 3

    counts = Counter(record["owner_status"] for record in records)
    assert counts == {OWNER_CONTEXT_DEPENDENT: 567, OWNER_UNRESOLVED: 2}
    assert sum(record["execution_eligible"] for record in records) == 0
    checks += 2

    for fixture in REAL_CONTEXT_FIXTURES:
        record = by_identity.get(fixture)
        assert record is not None
        assert record["owner_status"] == OWNER_CONTEXT_DEPENDENT
        assert record["execution_eligible"] is False
        assert "calcrev_runtime_interface" in record["evidence_source_ids"]
        assert "leaguebuilder_context_execution" in record["evidence_source_ids"]
        checks += 5

    for champion, slot, path in UNKNOWN_HASH_FIXTURES:
        matches = [
            record
            for record in records
            if record["champion"] == champion
            and record["slot"] == slot
            and record["graph_path"] == path
        ]
        assert len(matches) == 1
        assert matches[0]["owner_status"] == OWNER_UNRESOLVED
        assert matches[0]["execution_eligible"] is False
        checks += 3

    assert all(row["source_provenance"]["source_commit"] == PINNED_DATAMINE_COMMIT for row in rows)
    assert all(row["parent_calculation_identity"] for row in rows)
    assert all(row["root_calculation_identity"] for row in rows)
    assert all("ancestor_context" in row and "child_subpart_structure" in row for row in rows)
    assert sum(row["tooltip_linkage"]["status"] == "PINNED_TOOLTIP_CALCULATION_LINK_FOUND" for row in rows) == 461
    checks += 5

    print(
        "Champion spell stat owner precision checks: "
        f"PASS ({checks}/{checks}; {len(REAL_CONTEXT_FIXTURES)} context fixtures, "
        f"{len(UNKNOWN_HASH_FIXTURES)} unresolved-hash fixtures)"
    )


if __name__ == "__main__":
    main()
