"""Minimized non-circular fixtures from the exact pinned 26.16 source."""

from knowledge.champion_spell_stat_semantics import (
    BONUS_STAT,
    TOTAL_STAT,
    build_formula_semantic_records,
    build_stat_semantic_records,
    get_validated_stat_formula_mapping,
    get_validated_stat_mapping,
    inventory_stat_semantic_occurrences,
    stat_reference_rows,
)
from knowledge.champion_spell_stat_semantics_sources import PINNED_DATAMINE_COMMIT
from knowledge.pinned_spell_catalog_cache import get_pinned_spell_catalog


# Expected semantics are independently fixed from GlobalStatsUIData and the
# cited official mechanic sources; they are not generated by the mapper.
STAT_FIXTURES = [
    ("Amumu", "E", "DamageReduction", "mSpellCalculations/DamageReduction/mFormulaParts/1", 1, "ARMOR"),
    ("Malphite", "E", "EDamageCalc", "mSpellCalculations/EDamageCalc/mFormulaParts/1", 1, "ARMOR"),
    ("Aatrox", "Q", "QDamage", "mSpellCalculations/QDamage/mFormulaParts/1", 2, "ATTACK_DAMAGE"),
    ("Akshan", "Q", "FinalDamage", "mSpellCalculations/FinalDamage/mFormulaParts/1", 2, "ATTACK_DAMAGE"),
    ("Braum", "Q", "TotalDamage", "mSpellCalculations/TotalDamage/mFormulaParts/1", 12, "HEALTH"),
    ("Diana", "W", "ShieldValue", "mSpellCalculations/ShieldValue/mFormulaParts/2", 12, "HEALTH"),
]

FORMULA_FIXTURES = [
    ("Aatrox", "Q", "QDamage", "mSpellCalculations/QDamage/mFormulaParts/1", 2, 0, TOTAL_STAT, "riot_patch_9_2"),
    ("Malphite", "E", "EDamageCalc", "mSpellCalculations/EDamageCalc/mFormulaParts/1", 1, 0, TOTAL_STAT, "riot_patch_26_2"),
    ("Akshan", "Q", "FinalDamage", "mSpellCalculations/FinalDamage/mFormulaParts/1", 2, 2, BONUS_STAT, "riot_patch_26_1"),
    ("Diana", "W", "ShieldValue", "mSpellCalculations/ShieldValue/mFormulaParts/2", 12, 2, BONUS_STAT, "riot_patch_9_24"),
]


def main():
    catalog = get_pinned_spell_catalog()
    rows = stat_reference_rows(inventory_stat_semantic_occurrences(catalog))
    stat_records = build_stat_semantic_records(sorted({row["raw_mStat"] for row in rows}), rows)
    formula_records = build_formula_semantic_records(
        sorted({row["effective_mStatFormula"] for row in rows}), rows
    )
    stat_map = get_validated_stat_mapping(stat_records)
    formula_map = get_validated_stat_formula_mapping(formula_records)
    checks = 0

    assert set(stat_map) == {1, 2, 12}; checks += 1
    for champion, slot, key, path, raw_stat, expected in STAT_FIXTURES:
        matches = [
            row for row in rows
            if (row["champion_id"], row["slot"], row["calculation_key"], row["graph_path"], row["raw_mStat"])
            == (champion, slot, key, path, raw_stat)
        ]
        assert len(matches) == 1
        assert matches[0]["pinned_commit"] == PINNED_DATAMINE_COMMIT
        assert stat_map[raw_stat] == expected
        checks += 3

    for champion, slot, key, path, raw_stat, raw_formula, expected, source_id in FORMULA_FIXTURES:
        matches = [
            row for row in rows
            if (row["champion_id"], row["slot"], row["calculation_key"], row["graph_path"], row["raw_mStat"], row["effective_mStatFormula"])
            == (champion, slot, key, path, raw_stat, raw_formula)
        ]
        assert len(matches) == 1
        assert formula_map[raw_formula] == expected
        assert source_id in {item["source_id"] for item in formula_records[raw_formula]["evidence"]}
        checks += 3

    print(f"Champion spell stat semantics precision checks: PASS ({checks}/{checks}; {len(STAT_FIXTURES)} stat fixtures, {len(FORMULA_FIXTURES)} formula fixtures)")


if __name__ == "__main__":
    main()
